
FROM bkimminich/juice-shop:v13.3.0

ENV DEBIAN_FRONTEND=noninteractive
LABEL maintainer="Lab de JuiceShop"
LABEL description="juiceShop para laboratorio de pentesting"

EXPOSE 3000
CMD ["npm", "start"]

